# Generated by Django 5.0 on 2023-12-28 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.CharField(blank=True, max_length=255, verbose_name='відео'),
        ),
    ]
