# Generated by Django 5.0 on 2024-01-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Бренд'),
        ),
        migrations.AddField(
            model_name='product',
            name='display',
            field=models.FloatField(blank=True, null=True, verbose_name='Діагональ дисплея'),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.IntegerField(blank=True, null=True, verbose_name='ОЗП'),
        ),
        migrations.AddField(
            model_name='product',
            name='rom',
            field=models.IntegerField(blank=True, null=True, verbose_name='ПЗП'),
        ),
    ]
