# Generated by Django 5.0 on 2024-01-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_product_brand_product_display_product_ram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='display',
            field=models.IntegerField(blank=True, null=True, verbose_name='Діагональ дисплея'),
        ),
    ]
